# Generated by Django 5.1rc1 on 2024-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
